- futures/filters/america.json
https://trello.com/c/fxnMyG80/142-%D0%BD%D0%B0-futures-quotes-page-%D0%BD%D0%B5-%D1%85%D0%B2%D0%B0%D1%82%D0%B0%D0%B5%D1%82-%D0%BC%D0%BD%D0%BE%D0%B3%D0%B8%D1%85-%D0%BF%D0%BE%D0%BF%D1%83%D0%BB%D1%8F%D1%80%D0%BD%D1%8B%D1%85-%D1%81%D0%B8%D0%BC%D0%B2%D0%BE%D0%BB%D0%BE%D0%B2
Добавлены только американские фьючерсы
> Add new futures

- index/attributes/america.json
https://trello.com/c/darwoq1P/237
> Replace SP:SPF on INDEX:SRFI

- index/attributes/america.json
Reverts multicharts/scanner_data#11
> Revert "Replace SP:SPF on INDEX:SRFI"

- scanner.data.pine
https://xbugs.tradingview.com/browse/BS-3034
> Improve detect rule for doji candle

- crypto/groups/native_groups.json
https://xbugs.tradingview.com/browse/DEVOPS-2806
> DEVOPS-2806: add gemini crypto group

- crypto/groups/native_groups.json
Reverts multicharts/scanner_data#17 
префикс ловеркейсом ... gemini:ETHBTC
> Revert "DEVOPS-2806: add gemini crypto group"

- crypto/groups/native_groups.json
Reverts multicharts/scanner_data#18
> Revert "Revert "DEVOPS-2806: add gemini crypto group""

- cfd/filters/cfd.json
- cfd/filters/generator/main.js
- crypto/attributes/crypto.json
- scanner.data.pine
For test
https://xbugs.tradingview.com/browse/BS-4200
> Change harami candlestick formula

- stock/filters/generator/package-lock.json
- stock/filters/germany.frankfurt.json
- stock/filters/germany.stuttgart.json
https://tradingview.slack.com/archives/C9JK2NN9W/p1538978762000100
> Auto update stocks symbolinfo 08-10-18_09-05

- futures/filters/america.json
https://tradingview.slack.com/archives/C9JK2NN9W/p1538979119000100
> Auto update futures symbolinfo 08-10-18_09-11

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C455B0B25/p1543494938271300
> XRP instead Ripple

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C455B0B25/p1543494938271300
> Rename Ripple to XRP

- stock/filters/germany.frankfurt.json
- stock/filters/germany.stuttgart.json
https://tradingview.slack.com/archives/C9JK2NN9W/p1548223610067400
> Auto update stocks symbolinfo 23-01-19_09-05

- futures/filters/america.json
- stock/filters/germany.frankfurt.json
- stock/filters/germany.stuttgart.json
https://tradingview.slack.com/archives/C9JK2NN9W/p1551074814007800
> Auto update symbolinfo

- futures/groups/list.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1556380059044900
> HOTFIX: del comex_mini_migration_by_migration

- futures/groups/list.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1556385664055200?thread_ts=1556380059.044900&cid=C0PSLSK4P
> HOTFIX: del comex_mini_migration_by_migration 2

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1556566069105100
> Remove GBG,GOLOS,VRM

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-6138
> BS-6138: Remove milan_indices

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-6131
> BS-6131: replace moex_indices

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1560139481147700
> Remove some pairs from BITTREX

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C8EQFMXHQ/p1560139419042600
> Remove SALT

- futures/filters/america.json
- futures/filters/generator/america_continues.json
https://jira.xtools.tv/browse/BS-4761
> BS-4761: replace NYMEX:JMJ1! to NYMEX_MINI:MBC1!

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1565634180015800
> HOTFIX: add BITSTAMP:ETHUSD

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1565634180015800
> Return BINANCE symbols

- stock/filters/germany.frankfurt.json
- stock/filters/germany.stuttgart.json
https://tradingview.slack.com/archives/C9JK2NN9W/p1570687553000900
> Auto update stocks symbolinfo 10-10-19_09-05

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1571254471123500
> Remove CLAM, PASC

- stock/filters/germany.frankfurt.json
- stock/filters/germany.stuttgart.json
https://tradingview.slack.com/archives/C9JK2NN9W/p1577858754025500
> Auto update stocks symbolinfo 01-01-20_09-05

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C455B0B25/p1578584703009900
> HOTFIX: rename ATOBTC to Cosmos

- crypto/groups/native_prefix_exchanges.json
https://jira.xtools.tv/browse/BS-7716
> BS-7716: change BITPANDAGE to BITPANDAPRO

- scanner.data.pine
https://xbugs.tradingview.com/browse/BS-4200
> Remove C_IsDojiBody condition for Harami pattern

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C46E08VPH/p1588403212276400
> HOTFIX: remove invalid symbols crypto.json

- crypto/attributes/crypto.json
https://jira.xtools.tv/browse/BS-8033
> HOTFIX: remove bitfinex usd only

- crypto/attributes/crypto.json
- crypto/groups/native_groups.json
- crypto/groups/native_prefix_exchanges.json
https://jira.xtools.tv/browse/BS-8350
> BS-8350: remove-FTX

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-9073
> BS-9073: tvc migrate to cfd part1

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-9073
> BS-9073: tvc migrate to cfd pt.1

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1616847687481800
> Remove bunch bitfinex symbols

- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-9832
> BS-9832: add nasdaq_cfd_indices

- crypto/attributes/crypto.json
https://github.com/multicharts/scanner_data/pull/503/
> HOTFIX: try fix merge conflict

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-9836
> BS-9836: migrate us_ny_indices

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-10253
https://jira.xtools.tv/browse/BS-10254
> migrate singapore_tvc_indices us_chicago_indices

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-9838
> BS-9838: migrate british_indices

- stock/filters/germany.frankfurt.json
- stock/filters/germany.stuttgart.json
https://tradingview.slack.com/archives/C9JK2NN9W/p1622181968097800
> Auto update stocks symbolinfo 28-05-21_09-05

- cfd/filters/generator/main.js
- cfd/groups/indices.json
https://jira.xtools.tv/browse/BS-9838
> BS-9838: migrate british_indices in master

- stock/filters/germany.berlin.json
- stock/filters/germany.dusseldorf.json
- stock/filters/germany.hamburg.json
- stock/filters/germany.hannover.json
- stock/filters/germany.munchen.json
https://jira.xtools.tv/browse/BS-10449
> BS-10449: add regional germany exchanges

- crypto/attributes/crypto.json
Global Rental Token - The Graph
source:
https://research.binance.com/en/projects/the-graph
https://coinmarketcap.com/currencies/the-graph/
> Edit description of GRT token

- crypto/groups/native_prefix_exchanges.json
[BS-12186](https://jira.xtools.tv/browse/BS-12186)
> Add COINEX prefix

- stock/filters/generator/germany.js
Reverts multicharts/scanner_data#715
> Revert "BS-7405"

- crypto/attributes/crypto.json
https://tradingview.slack.com/archives/C0PSLSK4P/p1660228468474679?thread_ts=1660218772.046569&cid=C0PSLSK4P
> HOTFIX: remove BIT

- crypto/attributes/crypto.json
BITTREX:GBYTEBTC
OKX:USTCBTC
BITTREX:TYCBTC
HITBTC:AUTOBTC
> HBS-0: update few symbols

- scanner.qf.json
Reverts multicharts/scanner_data#1165
> Revert "HBS-2747: add new fields to scanner qf"

- economics/representative_symbols.json
Reverts multicharts/scanner_data#1187
> Revert "HBS-2583:add market economics"
